/**
 * 球星特徵庫（2026-08 版，世界盃後）
 * PARTS: 可重用部件（zh 顯示名 / en 生成描述）。髮色膚色靠引擎染色，唔屬部件形狀。
 * STARS: 100 位球星 → 部件組合 + 染色建議。描述以每人「最入屋」嘅招牌look為準。
 */

export const PARTS = {
  hair: [
    { id: 'buzz', zh: '剷青短髮', en: 'a very short buzz cut hugging the scalp' },
    { id: 'microbuzz', zh: '極短貼頭', en: 'an ultra-short shaved-down buzz, almost bald' },
    { id: 'crop', zh: '短碎髮', en: 'a short textured crop with a subtle messy fringe' },
    { id: 'slickfade', zh: '側梳油頭漸變', en: 'a sharp skin fade with a glossy slicked top' },
    { id: 'sidepart', zh: '紳士側分', en: 'a neat classic side-parted short haircut' },
    { id: 'waves', zh: '波浪貼頭', en: 'short brushed waves with a low fade' },
    { id: 'twists', zh: '短捲繩', en: 'short sponge twists with a clean fade on the sides' },
    { id: 'afro', zh: '圓爆炸頭', en: 'a rounded medium afro of tight curls' },
    { id: 'curlytop', zh: '捲頂剷邊', en: 'a curly top fade, tight coils on top and shaved sides' },
    { id: 'midcurls', zh: '中長亂捲', en: 'shoulder-length loose messy curls' },
    { id: 'mane', zh: '獅子捲', en: 'a huge bouncy curly mane puffing out on all sides' },
    { id: 'flow', zh: '及肩順髮', en: 'smooth flowing shoulder-length hair tucked behind the ears' },
    { id: 'bun', zh: '束髻', en: 'long hair tied back in a low bun' },
    { id: 'longband', zh: '長髮髮帶', en: 'long straight loose hair held by a thin sports headband' },
    { id: 'headbandslick', zh: '髮箍後梳', en: 'medium hair slicked straight back with a visible headband' },
    { id: 'slickback', zh: '全後梳', en: 'medium-length hair slicked straight back' },
    { id: 'twoblock', zh: '韓式碎蔭', en: 'a soft two-block haircut with a straight fringe over the forehead' },
    { id: 'spiky', zh: '碎立短髮', en: 'short choppy spiky hair' },
    { id: 'softmid', zh: '軟性側掃', en: 'soft medium-length hair swept gently to one side' },
    { id: 'mop', zh: '蓬鬆亂髮', en: 'a thick messy mop of loose waves' },
    { id: 'curtains', zh: '中分窗簾', en: 'middle-parted curtain bangs falling to both sides' },
    { id: 'braids', zh: '辮子', en: 'neat medium braids' },
    { id: 'highfore', zh: '高額短髮', en: 'short slightly wavy hair with a high forehead hairline' },
    { id: 'mullet', zh: '狐尾 Mullet', en: 'a modern mullet, short on top with a longer back' }
  ],
  eye: [
    { id: 'round_bright', zh: '圓大明亮', en: 'big round bright friendly eyes' },
    { id: 'droopy_calm', zh: '微垂溫柔', en: 'gentle downward-sloping calm eyes' },
    { id: 'sharp_narrow', zh: '銳利細長', en: 'sharp narrow determined eyes' },
    { id: 'deepset', zh: '深邃眼窩', en: 'deep-set intense eyes with defined lids' },
    { id: 'smiley_arc', zh: '瞇瞇笑月牙', en: 'happy closed arc-shaped smiling eyes' },
    { id: 'ice_stare', zh: '冰冷直視', en: 'piercing icy wide-open stare' },
    { id: 'big_expressive', zh: '大眼靈動', en: 'large lively expressive eyes with a playful sparkle' },
    { id: 'hooded', zh: '內斂單瞼', en: 'calm hooded single-lid eyes' },
    { id: 'gentle', zh: '八字友善', en: 'soft friendly slightly droopy eyes' },
    { id: 'frown_focus', zh: '皺眉專注', en: 'focused eyes under a slight concentration frown' }
  ],
  brow: [
    { id: 'thick_straight', zh: '濃一字眉', en: 'thick straight bold eyebrows' },
    { id: 'thick_arch', zh: '濃挑眉', en: 'thick well-groomed arched eyebrows' },
    { id: 'bushy', zh: '粗亂濃眉', en: 'bushy untamed heavy eyebrows' },
    { id: 'thin_light', zh: '幼淡眉', en: 'thin light-colored subtle eyebrows' },
    { id: 'fierce_angled', zh: '倒豎惡眉', en: 'sharply angled fierce eyebrows' },
    { id: 'soft_curve', zh: '柔彎眉', en: 'soft gently curved eyebrows' },
    { id: 'slit', zh: '界眉', en: 'bold eyebrows with a shaved slit line' },
    { id: 'heavy_low', zh: '壓眼濃眉', en: 'heavy low-set brows close over the eyes' }
  ],
  mouth: [
    { id: 'soft_smile', zh: '淺笑', en: 'a small soft closed smile' },
    { id: 'smirk', zh: '自信奸笑', en: 'a confident one-sided smirk' },
    { id: 'big_grin', zh: '露齒大笑', en: 'a wide beaming grin showing teeth' },
    { id: 'pout_smile', zh: '嘟嘴笑', en: 'a playful pouting smile with fuller lips' },
    { id: 'tight_line', zh: '抿嘴一字', en: 'a firm straight closed mouth' },
    { id: 'toothy', zh: '大板牙笑', en: 'a cheeky smile with prominent front teeth' },
    { id: 'shout', zh: '吶喊', en: 'a wide open shouting celebration mouth' },
    { id: 'tongue', zh: '吐脷慶祝', en: 'a cheeky smile with tongue sticking out' },
    { id: 'baby_smile', zh: '童顏甜笑', en: 'a sweet innocent boyish smile' },
    { id: 'serious_down', zh: '落角嚴肅', en: 'a serious mouth with slightly downturned corners' },
    { id: 'braces_grin', zh: '箍牙露齒笑', en: 'a beaming youthful grin showing teeth with tiny colorful braces brackets' }
  ],
  beard: [
    { id: 'none', zh: '無', en: '' },
    { id: 'stubble', zh: '鬚根', en: 'light even stubble' },
    { id: 'full_short', zh: '短絡腮', en: 'a neat short full beard along the jaw' },
    { id: 'full_dense', zh: '濃密大鬍', en: 'a dense full dark beard' },
    { id: 'goatee', zh: '山羊鬚', en: 'a trimmed goatee around the mouth and chin' },
    { id: 'chinstrap', zh: '貼邊細鬚', en: 'a thin sharply-lined chinstrap beard' },
    { id: 'moustache', zh: '兩撇雞', en: 'a bold moustache with a bare chin' },
    { id: 'scruffy', zh: '邋遢亂鬚', en: 'scruffy uneven scraggly facial hair' },
    { id: 'line_trim', zh: '精修界線', en: 'precisely trimmed thin beard lines' },
    { id: 'soul', zh: '下巴小撮', en: 'a small soul patch under the lip' }
  ]
};

// hairColor: 黑/深啡/啡/金/漂金/薑黃/灰白 · skin: 淺/中/深
export const STARS = [
  { n: '美斯 Messi', hair: 'crop', eye: 'droopy_calm', brow: 'bushy', mouth: 'soft_smile', beard: 'full_short', hairColor: '深啡', skin: '淺' },
  { n: 'C朗拿度 Cristiano Ronaldo', hair: 'slickfade', eye: 'sharp_narrow', brow: 'thick_arch', mouth: 'smirk', beard: 'stubble', hairColor: '黑', skin: '淺' },
  { n: '麥巴比 Mbappé', hair: 'buzz', eye: 'round_bright', brow: 'soft_curve', mouth: 'pout_smile', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '夏蘭特 Haaland', hair: 'longband', eye: 'ice_stare', brow: 'thin_light', mouth: 'tight_line', beard: 'stubble', hairColor: '金', skin: '淺' },
  { n: '尼馬 Neymar', hair: 'curlytop', eye: 'big_expressive', brow: 'soft_curve', mouth: 'big_grin', beard: 'line_trim', hairColor: '漂金', skin: '中' },
  { n: '貝寧咸 Bellingham', hair: 'twists', eye: 'round_bright', brow: 'thick_straight', mouth: 'big_grin', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '雲尼修斯 Vinícius Jr', hair: 'waves', eye: 'big_expressive', brow: 'thick_arch', mouth: 'big_grin', beard: 'line_trim', hairColor: '黑', skin: '深' },
  { n: '洛迪 Rodri', hair: 'mop', eye: 'frown_focus', brow: 'thick_straight', mouth: 'tight_line', beard: 'stubble', hairColor: '深啡', skin: '淺' },
  { n: '拿明耶馬 Lamine Yamal', hair: 'curlytop', eye: 'round_bright', brow: 'slit', mouth: 'braces_grin', beard: 'none', hairColor: '黑', skin: '中', extra: '紅藍/星形箍牙（TwoJeys 聯名）' },
  { n: '甸比利 Dembélé', hair: 'crop', eye: 'gentle', brow: 'soft_curve', mouth: 'soft_smile', beard: 'chinstrap', hairColor: '黑', skin: '深' },
  { n: '沙拿 Salah', hair: 'afro', eye: 'smiley_arc', brow: 'bushy', mouth: 'big_grin', beard: 'full_dense', hairColor: '黑', skin: '中' },
  { n: '哈利卡尼 Kane', hair: 'sidepart', eye: 'gentle', brow: 'thick_straight', mouth: 'soft_smile', beard: 'stubble', hairColor: '啡', skin: '淺' },
  { n: '孫興慜 Son', hair: 'twoblock', eye: 'smiley_arc', brow: 'soft_curve', mouth: 'big_grin', beard: 'none', hairColor: '黑', skin: '淺' },
  { n: '迪布尼 De Bruyne', hair: 'highfore', eye: 'gentle', brow: 'thin_light', mouth: 'serious_down', beard: 'stubble', hairColor: '薑黃', skin: '淺' },
  { n: '慕西亞拉 Musiala', hair: 'twists', eye: 'round_bright', brow: 'soft_curve', mouth: 'baby_smile', beard: 'none', hairColor: '黑', skin: '中' },
  { n: '域斯 Wirtz', hair: 'softmid', eye: 'round_bright', brow: 'thin_light', mouth: 'baby_smile', beard: 'none', hairColor: '啡', skin: '淺' },
  { n: '比德利 Pedri', hair: 'softmid', eye: 'droopy_calm', brow: 'soft_curve', mouth: 'soft_smile', beard: 'none', hairColor: '深啡', skin: '淺' },
  { n: '加維 Gavi', hair: 'mop', eye: 'deepset', brow: 'thick_straight', mouth: 'shout', beard: 'none', hairColor: '深啡', skin: '淺' },
  { n: '坎巴斯 Cubarsí', hair: 'curtains', eye: 'round_bright', brow: 'thick_straight', mouth: 'baby_smile', beard: 'none', hairColor: '深啡', skin: '淺' },
  { n: '尼高威廉斯 Nico Williams', hair: 'twists', eye: 'big_expressive', brow: 'slit', mouth: 'big_grin', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '奧莫 Dani Olmo', hair: 'crop', eye: 'gentle', brow: 'soft_curve', mouth: 'soft_smile', beard: 'stubble', hairColor: '啡', skin: '淺' },
  { n: '烏奈西蒙 Unai Simón', hair: 'crop', eye: 'frown_focus', brow: 'thick_straight', mouth: 'tight_line', beard: 'stubble', hairColor: '深啡', skin: '淺' },
  { n: '拉芬夏 Raphinha', hair: 'crop', eye: 'sharp_narrow', brow: 'thick_arch', mouth: 'smirk', beard: 'line_trim', hairColor: '深啡', skin: '中' },
  { n: '利雲度夫斯基 Lewandowski', hair: 'sidepart', eye: 'sharp_narrow', brow: 'thick_straight', mouth: 'soft_smile', beard: 'stubble', hairColor: '啡', skin: '淺' },
  { n: '郭圖爾斯 Courtois', hair: 'sidepart', eye: 'gentle', brow: 'soft_curve', mouth: 'serious_down', beard: 'stubble', hairColor: '深啡', skin: '淺' },
  { n: '維天拿 Vitinha', hair: 'crop', eye: 'droopy_calm', brow: 'soft_curve', mouth: 'soft_smile', beard: 'stubble', hairColor: '深啡', skin: '淺' },
  { n: '杜爾 Doué', hair: 'twists', eye: 'round_bright', brow: 'soft_curve', mouth: 'baby_smile', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '巴高拿 Barcola', hair: 'twists', eye: 'big_expressive', brow: 'soft_curve', mouth: 'big_grin', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '哈基米 Hakimi', hair: 'waves', eye: 'sharp_narrow', brow: 'thick_arch', mouth: 'big_grin', beard: 'chinstrap', hairColor: '黑', skin: '中' },
  { n: '祖奧尼維斯 João Neves', hair: 'mop', eye: 'round_bright', brow: 'thick_straight', mouth: 'baby_smile', beard: 'none', hairColor: '深啡', skin: '淺' },
  { n: '唐拿隆馬 Donnarumma', hair: 'slickback', eye: 'gentle', brow: 'thick_straight', mouth: 'tight_line', beard: 'stubble', hairColor: '深啡', skin: '淺' },
  { n: '沙耶艾馬利 Zaïre-Emery', hair: 'buzz', eye: 'frown_focus', brow: 'thick_straight', mouth: 'tight_line', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '卓基 Cherki', hair: 'curlytop', eye: 'deepset', brow: 'thick_arch', mouth: 'smirk', beard: 'none', hairColor: '黑', skin: '中' },
  { n: '奧利斯 Olise', hair: 'twists', eye: 'droopy_calm', brow: 'soft_curve', mouth: 'soft_smile', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '杜林 Marcus Thuram', hair: 'buzz', eye: 'big_expressive', brow: 'thick_straight', mouth: 'big_grin', beard: 'chinstrap', hairColor: '黑', skin: '深' },
  { n: '簡迪 Kanté', hair: 'microbuzz', eye: 'smiley_arc', brow: 'soft_curve', mouth: 'big_grin', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '米倫 Maignan', hair: 'microbuzz', eye: 'sharp_narrow', brow: 'thick_straight', mouth: 'tight_line', beard: 'chinstrap', hairColor: '黑', skin: '深' },
  { n: '泰奧 Theo Hernández', hair: 'flow', eye: 'sharp_narrow', brow: 'thick_arch', mouth: 'smirk', beard: 'stubble', hairColor: '深啡', skin: '淺' },
  { n: '昆迪 Koundé', hair: 'braids', eye: 'droopy_calm', brow: 'soft_curve', mouth: 'tight_line', beard: 'chinstrap', hairColor: '黑', skin: '深' },
  { n: '普巴 Pogba', hair: 'curlytop', eye: 'big_expressive', brow: 'thick_arch', mouth: 'big_grin', beard: 'goatee', hairColor: '漂金', skin: '深' },
  { n: '基沙文 Griezmann', hair: 'slickback', eye: 'gentle', brow: 'thin_light', mouth: 'smirk', beard: 'moustache', hairColor: '啡', skin: '淺' },
  { n: '艾華利斯 Julián Álvarez', hair: 'crop', eye: 'round_bright', brow: 'soft_curve', mouth: 'baby_smile', beard: 'none', hairColor: '深啡', skin: '淺' },
  { n: '華維迪 Valverde', hair: 'mullet', eye: 'sharp_narrow', brow: 'thick_straight', mouth: 'tight_line', beard: 'stubble', hairColor: '深啡', skin: '中' },
  { n: '甘馬雲加 Camavinga', hair: 'braids', eye: 'big_expressive', brow: 'soft_curve', mouth: 'big_grin', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '祖亞文尼 Tchouaméni', hair: 'twists', eye: 'frown_focus', brow: 'thick_straight', mouth: 'soft_smile', beard: 'chinstrap', hairColor: '黑', skin: '深' },
  { n: '洛迪加 Rüdiger', hair: 'buzz', eye: 'ice_stare', brow: 'fierce_angled', mouth: 'big_grin', beard: 'chinstrap', hairColor: '黑', skin: '深' },
  { n: '卡華哈爾 Carvajal', hair: 'crop', eye: 'frown_focus', brow: 'thick_straight', mouth: 'tight_line', beard: 'full_short', hairColor: '深啡', skin: '淺' },
  { n: '奧巴克 Oblak', hair: 'sidepart', eye: 'frown_focus', brow: 'thick_straight', mouth: 'serious_down', beard: 'stubble', hairColor: '深啡', skin: '淺' },
  { n: '費明 Fermín López', hair: 'crop', eye: 'round_bright', brow: 'thick_straight', mouth: 'shout', beard: 'none', hairColor: '深啡', skin: '淺' },
  { n: '沙卡 Saka', hair: 'twists', eye: 'smiley_arc', brow: 'soft_curve', mouth: 'big_grin', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '科登 Foden', hair: 'buzz', eye: 'round_bright', brow: 'thin_light', mouth: 'soft_smile', beard: 'none', hairColor: '金', skin: '淺' },
  { n: '龐馬 Palmer', hair: 'crop', eye: 'droopy_calm', brow: 'thin_light', mouth: 'serious_down', beard: 'none', hairColor: '深啡', skin: '淺' },
  { n: '賴斯 Rice', hair: 'crop', eye: 'gentle', brow: 'thick_straight', mouth: 'big_grin', beard: 'stubble', hairColor: '深啡', skin: '淺' },
  { n: '奧迪加特 Ødegaard', hair: 'sidepart', eye: 'droopy_calm', brow: 'thin_light', mouth: 'soft_smile', beard: 'stubble', hairColor: '金', skin: '淺' },
  { n: '基利殊 Grealish', hair: 'headbandslick', eye: 'big_expressive', brow: 'thick_arch', mouth: 'smirk', beard: 'stubble', hairColor: '深啡', skin: '淺' },
  { n: '拉舒福特 Rashford', hair: 'waves', eye: 'droopy_calm', brow: 'thick_straight', mouth: 'soft_smile', beard: 'chinstrap', hairColor: '黑', skin: '深' },
  { n: '賓費南迪斯 Bruno Fernandes', hair: 'highfore', eye: 'deepset', brow: 'thick_straight', mouth: 'serious_down', beard: 'full_short', hairColor: '深啡', skin: '淺' },
  { n: '加拿祖 Garnacho', hair: 'mullet', eye: 'big_expressive', brow: 'thick_arch', mouth: 'smirk', beard: 'none', hairColor: '漂金', skin: '淺' },
  { n: '緬奴 Mainoo', hair: 'twists', eye: 'round_bright', brow: 'soft_curve', mouth: 'baby_smile', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '伊薩克 Isak', hair: 'curlytop', eye: 'droopy_calm', brow: 'soft_curve', mouth: 'soft_smile', beard: 'stubble', hairColor: '黑', skin: '深' },
  { n: '雲戴克 Van Dijk', hair: 'bun', eye: 'ice_stare', brow: 'heavy_low', mouth: 'tight_line', beard: 'full_short', hairColor: '黑', skin: '深' },
  { n: '阿諾特 Alexander-Arnold', hair: 'curlytop', eye: 'gentle', brow: 'thick_straight', mouth: 'soft_smile', beard: 'line_trim', hairColor: '深啡', skin: '中' },
  { n: '凱塞多 Caicedo', hair: 'twists', eye: 'frown_focus', brow: 'thick_straight', mouth: 'tight_line', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '恩素 Enzo Fernández', hair: 'crop', eye: 'sharp_narrow', brow: 'thick_straight', mouth: 'soft_smile', beard: 'stubble', hairColor: '深啡', skin: '淺' },
  { n: '麥亞里士打 Mac Allister', hair: 'crop', eye: 'gentle', brow: 'thick_straight', mouth: 'soft_smile', beard: 'full_short', hairColor: '深啡', skin: '淺' },
  { n: '度古 Doku', hair: 'twists', eye: 'big_expressive', brow: 'soft_curve', mouth: 'big_grin', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '大馬天尼斯 Emi Martínez', hair: 'slickback', eye: 'sharp_narrow', brow: 'thick_arch', mouth: 'smirk', beard: 'scruffy', hairColor: '深啡', skin: '淺' },
  { n: '加普 Gakpo', hair: 'waves', eye: 'droopy_calm', brow: 'thick_straight', mouth: 'soft_smile', beard: 'chinstrap', hairColor: '黑', skin: '深' },
  { n: '紐尼斯 Núñez', hair: 'crop', eye: 'sharp_narrow', brow: 'fierce_angled', mouth: 'shout', beard: 'stubble', hairColor: '黑', skin: '中' },
  { n: '阿利臣 Alisson', hair: 'crop', eye: 'gentle', brow: 'thick_straight', mouth: 'soft_smile', beard: 'full_dense', hairColor: '深啡', skin: '淺' },
  { n: '艾達臣 Ederson', hair: 'slickback', eye: 'sharp_narrow', brow: 'thick_arch', mouth: 'tight_line', beard: 'full_short', hairColor: '深啡', skin: '中' },
  { n: '魯賓迪亞斯 Rúben Dias', hair: 'crop', eye: 'frown_focus', brow: 'heavy_low', mouth: 'serious_down', beard: 'full_short', hairColor: '黑', skin: '淺' },
  { n: '般奴施華 Bernardo Silva', hair: 'softmid', eye: 'droopy_calm', brow: 'soft_curve', mouth: 'soft_smile', beard: 'full_short', hairColor: '深啡', skin: '淺' },
  { n: '賓斯馬 Benzema', hair: 'buzz', eye: 'sharp_narrow', brow: 'thick_arch', mouth: 'soft_smile', beard: 'full_dense', hairColor: '黑', skin: '中' },
  { n: '基米希 Kimmich', hair: 'sidepart', eye: 'frown_focus', brow: 'thin_light', mouth: 'tight_line', beard: 'stubble', hairColor: '啡', skin: '淺' },
  { n: '紐亞 Neuer', hair: 'sidepart', eye: 'ice_stare', brow: 'thin_light', mouth: 'serious_down', beard: 'stubble', hairColor: '金', skin: '淺' },
  { n: '沙尼 Sané', hair: 'buzz', eye: 'droopy_calm', brow: 'soft_curve', mouth: 'soft_smile', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '勞塔羅 Lautaro Martínez', hair: 'crop', eye: 'sharp_narrow', brow: 'fierce_angled', mouth: 'shout', beard: 'stubble', hairColor: '黑', skin: '中' },
  { n: '巴里拿 Barella', hair: 'crop', eye: 'deepset', brow: 'thick_straight', mouth: 'serious_down', beard: 'stubble', hairColor: '深啡', skin: '淺' },
  { n: '里奧 Rafael Leão', hair: 'twists', eye: 'droopy_calm', brow: 'slit', mouth: 'big_grin', beard: 'none', hairColor: '漂金', skin: '深' },
  { n: '卡華拉斯基利亞 Kvaratskhelia', hair: 'midcurls', eye: 'deepset', brow: 'bushy', mouth: 'serious_down', beard: 'scruffy', hairColor: '黑', skin: '淺' },
  { n: '奧斯文 Osimhen', hair: 'curlytop', eye: 'big_expressive', brow: 'thick_straight', mouth: 'toothy', beard: 'none', hairColor: '漂金', skin: '深' },
  { n: '耶迪斯 Yıldız', hair: 'softmid', eye: 'deepset', brow: 'thick_straight', mouth: 'soft_smile', beard: 'none', hairColor: '深啡', skin: '淺' },
  { n: '摩迪 Modrić', hair: 'flow', eye: 'droopy_calm', brow: 'thin_light', mouth: 'soft_smile', beard: 'stubble', hairColor: '啡', skin: '淺' },
  { n: '古拿 Arda Güler', hair: 'softmid', eye: 'round_bright', brow: 'soft_curve', mouth: 'baby_smile', beard: 'none', hairColor: '深啡', skin: '淺' },
  { n: '佐克利斯 Gyökeres', hair: 'slickback', eye: 'ice_stare', brow: 'thin_light', mouth: 'tight_line', beard: 'stubble', hairColor: '金', skin: '淺' },
  { n: '塞斯高 Sesko', hair: 'crop', eye: 'ice_stare', brow: 'thin_light', mouth: 'tight_line', beard: 'none', hairColor: '啡', skin: '淺' },
  { n: '沙維西蒙斯 Xavi Simons', hair: 'curlytop', eye: 'big_expressive', brow: 'thick_arch', mouth: 'smirk', beard: 'none', hairColor: '深啡', skin: '中' },
  { n: '文尼 Mané', hair: 'buzz', eye: 'smiley_arc', brow: 'soft_curve', mouth: 'big_grin', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '金玟哉 Kim Min-jae', hair: 'twoblock', eye: 'hooded', brow: 'thick_straight', mouth: 'tight_line', beard: 'none', hairColor: '黑', skin: '淺' },
  { n: '三笘薰 Mitoma', hair: 'spiky', eye: 'hooded', brow: 'soft_curve', mouth: 'soft_smile', beard: 'none', hairColor: '黑', skin: '淺' },
  { n: '久保建英 Kubo', hair: 'spiky', eye: 'hooded', brow: 'thick_straight', mouth: 'baby_smile', beard: 'none', hairColor: '黑', skin: '淺' },
  { n: '李剛仁 Lee Kang-in', hair: 'twoblock', eye: 'hooded', brow: 'soft_curve', mouth: 'soft_smile', beard: 'none', hairColor: '黑', skin: '淺' },
  { n: '普利錫 Pulisic', hair: 'crop', eye: 'round_bright', brow: 'thin_light', mouth: 'baby_smile', beard: 'none', hairColor: '啡', skin: '淺' },
  { n: '戴維斯 Alphonso Davies', hair: 'twists', eye: 'big_expressive', brow: 'soft_curve', mouth: 'big_grin', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '恩迪克 Endrick', hair: 'curlytop', eye: 'round_bright', brow: 'thick_straight', mouth: 'baby_smile', beard: 'none', hairColor: '黑', skin: '深' },
  { n: '伊斯迪華奧 Estêvão', hair: 'curlytop', eye: 'round_bright', brow: 'soft_curve', mouth: 'baby_smile', beard: 'none', hairColor: '黑', skin: '中' },
  { n: '馬斯坦禾奴 Mastantuono', hair: 'curtains', eye: 'round_bright', brow: 'thick_straight', mouth: 'baby_smile', beard: 'none', hairColor: '啡', skin: '淺' },
  { n: '卡斯米路 Casemiro', hair: 'crop', eye: 'frown_focus', brow: 'bushy', mouth: 'serious_down', beard: 'stubble', hairColor: '黑', skin: '中' },
  { n: '蘇亞雷斯 Suárez', hair: 'crop', eye: 'deepset', brow: 'bushy', mouth: 'toothy', beard: 'scruffy', hairColor: '黑', skin: '中' }
];
